// Capacitor-compatible db.server using Supabase for cross-platform sync
// Re-exports from server/db.server since Supabase works in both browser and Capacitor
export {
  getAgentProfile,
  saveAgentProfile,
  listAgents,
  listAllAgents,
  getCustomerProfile,
  saveCustomerProfile,
  listCustomers,
  listAllCustomers,
  listCustomersByTier,
  getTransaction,
  saveTransaction,
  listTransactions,
  listAllTransactions,
  listTransactionsByAgent,
  listTransactionsByCustomer,
  listTransactionsByTier,
  getFloatRequest,
  saveFloatRequest,
  listFloatRequests,
  listAllFloatRequests,
  listFloatRequestsByAgent,
  getFloatExchange,
  saveFloatExchange,
  listFloatExchanges,
  listAllFloatExchanges,
  listFloatExchangesByAgent,
  getCreditPortfolio,
  listCreditPortfolios,
  deleteAgent,
  deleteCustomer,
  deleteTransaction,
  deleteFloatRequest,
  deleteFloatExchange,
  getVendorProfile,
  saveVendorProfile,
  listVendors,
  listAllVendors,
  listVendorsByStatus,
  deleteVendor,
  syncVendorsToSupabase,
  clearAllTestData,
} from '@/server/db.server'
