/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RegisterCustomerRouteImport } from './routes/register/customer'
import { Route as RegisterAgentRouteImport } from './routes/register/agent'
import { Route as CustomerServicesRouteImport } from './routes/customer/services'
import { Route as CustomerHistoryRouteImport } from './routes/customer/history'
import { Route as CustomerConfirmationRouteImport } from './routes/customer/confirmation'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AgentTransactionsRouteImport } from './routes/agent/transactions'
import { Route as AgentFloatRouteImport } from './routes/agent/float'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminFloatRequestsRouteImport } from './routes/admin/float-requests'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterCustomerRoute = RegisterCustomerRouteImport.update({
  id: '/register/customer',
  path: '/register/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAgentRoute = RegisterAgentRouteImport.update({
  id: '/register/agent',
  path: '/register/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServicesRoute = CustomerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerConfirmationRoute = CustomerConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => CustomerRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTransactionsRoute = AgentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AgentRoute,
} as any)
const AgentFloatRoute = AgentFloatRouteImport.update({
  id: '/float',
  path: '/float',
  getParentRoute: () => AgentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFloatRequestsRoute = AdminFloatRequestsRouteImport.update({
  id: '/float-requests',
  path: '/float-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/float-requests': typeof AdminFloatRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/float': typeof AgentFloatRoute
  '/agent/transactions': typeof AgentTransactionsRoute
  '/api/health': typeof ApiHealthRoute
  '/customer/confirmation': typeof CustomerConfirmationRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/services': typeof CustomerServicesRoute
  '/register/agent': typeof RegisterAgentRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/float-requests': typeof AdminFloatRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/float': typeof AgentFloatRoute
  '/agent/transactions': typeof AgentTransactionsRoute
  '/api/health': typeof ApiHealthRoute
  '/customer/confirmation': typeof CustomerConfirmationRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/services': typeof CustomerServicesRoute
  '/register/agent': typeof RegisterAgentRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/customer': typeof CustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/float-requests': typeof AdminFloatRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/float': typeof AgentFloatRoute
  '/agent/transactions': typeof AgentTransactionsRoute
  '/api/health': typeof ApiHealthRoute
  '/customer/confirmation': typeof CustomerConfirmationRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/services': typeof CustomerServicesRoute
  '/register/agent': typeof RegisterAgentRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/customer'
    | '/login'
    | '/admin/agents'
    | '/admin/customers'
    | '/admin/float-requests'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/agent/float'
    | '/agent/transactions'
    | '/api/health'
    | '/customer/confirmation'
    | '/customer/history'
    | '/customer/services'
    | '/register/agent'
    | '/register/customer'
    | '/admin/'
    | '/agent/'
    | '/customer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/agents'
    | '/admin/customers'
    | '/admin/float-requests'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/agent/float'
    | '/agent/transactions'
    | '/api/health'
    | '/customer/confirmation'
    | '/customer/history'
    | '/customer/services'
    | '/register/agent'
    | '/register/customer'
    | '/admin'
    | '/agent'
    | '/customer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/customer'
    | '/login'
    | '/admin/agents'
    | '/admin/customers'
    | '/admin/float-requests'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/agent/float'
    | '/agent/transactions'
    | '/api/health'
    | '/customer/confirmation'
    | '/customer/history'
    | '/customer/services'
    | '/register/agent'
    | '/register/customer'
    | '/admin/'
    | '/agent/'
    | '/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RegisterAgentRoute: typeof RegisterAgentRoute
  RegisterCustomerRoute: typeof RegisterCustomerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/customer': {
      id: '/register/customer'
      path: '/register/customer'
      fullPath: '/register/customer'
      preLoaderRoute: typeof RegisterCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/agent': {
      id: '/register/agent'
      path: '/register/agent'
      fullPath: '/register/agent'
      preLoaderRoute: typeof RegisterAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/services': {
      id: '/customer/services'
      path: '/services'
      fullPath: '/customer/services'
      preLoaderRoute: typeof CustomerServicesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/history': {
      id: '/customer/history'
      path: '/history'
      fullPath: '/customer/history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/confirmation': {
      id: '/customer/confirmation'
      path: '/confirmation'
      fullPath: '/customer/confirmation'
      preLoaderRoute: typeof CustomerConfirmationRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/transactions': {
      id: '/agent/transactions'
      path: '/transactions'
      fullPath: '/agent/transactions'
      preLoaderRoute: typeof AgentTransactionsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/float': {
      id: '/agent/float'
      path: '/float'
      fullPath: '/agent/float'
      preLoaderRoute: typeof AgentFloatRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/float-requests': {
      id: '/admin/float-requests'
      path: '/float-requests'
      fullPath: '/admin/float-requests'
      preLoaderRoute: typeof AdminFloatRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFloatRequestsRoute: typeof AdminFloatRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFloatRequestsRoute: AdminFloatRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentFloatRoute: typeof AgentFloatRoute
  AgentTransactionsRoute: typeof AgentTransactionsRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentFloatRoute: AgentFloatRoute,
  AgentTransactionsRoute: AgentTransactionsRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface CustomerRouteChildren {
  CustomerConfirmationRoute: typeof CustomerConfirmationRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerServicesRoute: typeof CustomerServicesRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerConfirmationRoute: CustomerConfirmationRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerServicesRoute: CustomerServicesRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  RegisterAgentRoute: RegisterAgentRoute,
  RegisterCustomerRoute: RegisterCustomerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
